version: '{branch}-{build}'
build: off
environment:
  matrix:
    - TOXENV: py39,codecov
      TOXPYTHON: C:\Python39-x64\python.exe
      PYTHON_HOME: C:\Python39-x64
      PYTHON_VERSION: '3.9'
      PYTHON_ARCH: '64'
    - TOXENV: py310,codecov
      TOXPYTHON: C:\Python310-x64\python.exe
      PYTHON_HOME: C:\Python310-x64
      PYTHON_VERSION: '3.10'
      PYTHON_ARCH: '64'
    - TOXENV: py311,codecov
      TOXPYTHON: C:\Python311-x64\python.exe
      PYTHON_HOME: C:\Python311-x64
      PYTHON_VERSION: '3.11'
      PYTHON_ARCH: '64'
    - TOXENV: py312,codecov
      TOXPYTHON: C:\Python312-x64\python.exe
      PYTHON_HOME: C:\Python312-x64
      PYTHON_VERSION: '3.12'
      PYTHON_ARCH: '64'

init:
  - ps: echo $env:TOXENV
  - ps: ls C:\Python*
install:
  - '%PYTHON_HOME%\python -mpip install --progress-bar=off tox -rci/requirements.txt'
  - '%PYTHON_HOME%\Scripts\virtualenv --version'
  - '%PYTHON_HOME%\Scripts\pip --version'
  - '%PYTHON_HOME%\Scripts\tox --version'
test_script:
  - cmd /E:ON /V:ON /C .\ci\appveyor-with-compiler.cmd %PYTHON_HOME%\Scripts\tox
on_failure:
  - ps: dir "env:"
  - ps: get-content .tox\*\log\*

### To enable remote debugging uncomment this (also, see: http://www.appveyor.com/docs/how-to/rdp-to-build-worker):
# on_finish:
#   - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
